[build]
  functions = "functions"

# rinkeby server redirect
[[redirects]]
  from = "/api/4/*"
  to = "http://164.92.233.6/:splat"

# rinkeby tokenURI redirect
[[redirects]]
  from = "/v1/metadata/*"
  to = "http://164.92.233.6/v1/metadata/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200