[build]
  functions = "functions"

[build.environment]
  NODE_VERSION = "16"

# rinkeby: port 3001
# mainnet: no port

# proxy server media
[[redirects]]
  from = "/gif/*"
  to = "https://folia-decomposer.fly.dev/gif/:splat"
  status = 200

# proxy server media
[[redirects]]
  from = "/get/*"
  to = "https://folia-decomposer.fly.dev/get/:splat"
  status = 200

# proxy server media
[[redirects]]
  from = "/stylesheets/*"
  to = "https://folia-decomposer.fly.dev/stylesheets/:splat"
  status = 200



# mainnent server proxy (no port)
  [[redirects]]
    from = "/api/1/*"
    to = "https://folia-decomposer.fly.dev/:splat"
    status = 200

# rinkeby server proxy
[[redirects]]
  from = "/api/4/*"
  to = "https://folia-decomposer.fly.dev/:splat"
  status = 200

# rinkeby tokenURI proxy
[[redirects]]
  from = "/v1/metadata/*"
  to = "https://folia-decomposer.fly.dev/v1/metadata/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200