export default [
  ['888 by Kevin Abosch', 'https://opensea.io/collection/888-by-kevin-abosch'],
  ['Archetype by Kjetil Golid', 'https://opensea.io/collection/archetype-by-kjetil-golid'],
  ['Blitmap', 'https://opensea.io/collection/blitmap'],
  ['Bored Ape Kennel Club', 'https://opensea.io/collection/bored-ape-kennel-club'],
  ['Bored Ape Yacht Club', 'https://opensea.io/collection/boredapeyachtclub'],
  ['Capsule House', 'https://opensea.io/collection/capsulehouse'],
  ['Chromie Squiggle by Snowfro', 'https://opensea.io/collection/chromie-squiggle-by-snowfro'],
  ['CLONE X - X TAKASHI MURAKAMI', 'https://opensea.io/collection/clonex'],
  ['Cool Cats NFT', 'https://opensea.io/collection/cool-cats-nft'],
  ['CrypToadz by GREMPLIN', 'https://opensea.io/collection/cryptoadz-by-gremplin'],
  ['CryptoArte', 'https://opensea.io/collection/cryptoarte'],
  ['CryptoBots', 'https://opensea.io/collection/cryptobots'],
  ['Crypto Coven', 'https://opensea.io/collection/cryptocoven'],
  ['CryptoKitties', 'https://opensea.io/collection/cryptokitties'],
  ['CyberKongz', 'https://opensea.io/collection/cyberkongz'],
  ['CryptoPunks', 'https://opensea.io/collection/cryptopunks'],
  ['CryptoSkulls', 'https://opensea.io/CryptoSkulls/cryptoskulls'],
  ['CryptoTulips', 'https://opensea.io/collection/cryptotulips'],
  ['Decentraland', 'https://opensea.io/collection/decentraland'],
  ['DotCom Seance', 'https://dotcomseance.com'],
  ['eBoy Blockbob', 'https://opensea.io/collection/eboy-blockbob'],
  ['Emoji Script by Travess Smalley', 'https://folia.app/works/2'],
  ['EtherRock'],
  ['ETH Pixels', 'https://opensea.io/collection/ethpixels'],
  ['Fast Food Frens Collection', 'https://opensea.io/collection/fastfoodfrenscollection'],
  ['Fast Food Punks', 'https://opensea.io/collection/fast-food-punks'],
  ['Fidenza by Tyler Hobbs', 'https://opensea.io/collection/fidenza-by-tyler-hobbs'],
  ['FOMO Dog Club', 'https://opensea.io/collection/fomo-dog-club'],
  ['Fragments of an Infinite Field by Monica Rizzolli', 'https://opensea.io/collection/fragments-of-an-infinite-field-by-monica-rizzolli'],
  ['Gutter Cat Gang', 'https://opensea.io/collection/guttercatgang'],
  ['Hashmasks', 'https://opensea.io/collection/hashmasks'],
  ['Lazy Lions', 'https://opensea.io/collection/lazy-lions'],
  ['lobsterdao', 'https://opensea.io/collection/lobsterdao'],
  ['MoonCats', 'https://opensea.io/collection/acclimatedmooncats'],
  ['Mutant Ape Yacht Club', 'https://opensea.io/collection/mutant-ape-yacht-club'],
  ['My Curio Cards', 'https://opensea.io/collection/curiocardswrapper'],
  ['Nouns', 'https://opensea.io/collection/nouns'],
  ['Parallel Alpha', 'https://opensea.io/collection/parallelalpha'],
  ['Petra Cortright - Room', 'https://opensea.io/collection/simco-drops-petra-cortright-room'],
  ['PhantaBear', 'https://opensea.io/collection/phantabear'],
  ['PixelMap', 'https://opensea.io/collection/pixelmap'],
  ['Pudgy Penguins', 'https://opensea.io/collection/pudgypenguins'],
  ['PunkScapes', 'https://opensea.io/collection/punkscapes'],
  ['Realiti', 'https://opensea.io/collection/realitic'],
  ['THE SHIBOSHIS', 'https://opensea.io/collection/theshiboshis'],
  ['World of Women', 'https://opensea.io/collection/world-of-women-nft'],
  ['Wrapped CryptoCats Official', 'https://opensea.io/collection/wrappedcryptocats'],
  ['Wrapped Pixereum', 'https://opensea.io/collection/wrapped-pixereum']
]
